export enum envEnum {
	SST_STAGE = 'SST_STAGE',
	LOG_LEVEL = 'LOG_LEVEL',
	POWERTOOLS_TRACER_CAPTURE_RESPONSE = 'POWERTOOLS_TRACER_CAPTURE_RESPONSE',
	POWERTOOLS_LOGGER_LOG_EVENT = 'POWERTOOLS_LOGGER_LOG_EVENT',
}
