name: Lind and build

on:
  pull_request:
    branches:
      - develop

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: 'Install dependencies'
        shell: bash
        run: npm ci
      - name: 'Codegen'
        shell: bash
        run: npm run codegen
      - name: 'Lint and build'
        shell: bash
        run: npm run build
